// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteTypeScript(arg1) {
  return window['go']['main']['App']['ExecuteTypeScript'](arg1);
}

export function GetChatState() {
  return window['go']['main']['App']['GetChatState']();
}

export function GetCurrentProjectTree() {
  return window['go']['main']['App']['GetCurrentProjectTree']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}
