// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetChatState():Promise<domain.ChatState>;

export function GetCurrentProjectTree():Promise<domain.Node>;

export function Greet(arg1:string):Promise<string>;

export function SendChatMessage(arg1:string):Promise<domain.ChatState>;
